### ISSUE TITLE
Rename option based on frame type output

### ISSUE THREAD

**Issue by Deathproof76** [hclivess/nameer#1] opened 2022-12-12 17:20 UTC
Hello,

would it be possible to rename a file based on the result of `ffprobe -show_frames input.mkv -read_intervals %+10 -hide_banner | grep pict_type=I -m 20` ? I currently have a really weird bug because of a beta driver, where a lot of my encodes are having only one single I-frame at the beginning of the file. That causes a lot of problems during playback and the files have to be reencoded.
I found out really late about this, so that I now have thousands of files which may or may not have this problem. 
I would be eternally greatful if there was an option like e.g. when there are less then two I-frames add _problem or something similar to the filename.

Many thanks!

**Comment by hclivess** [comment] 2022-12-13 00:39
That sounds doable, I'll check and let you know

**Comment by hclivess** [comment] 2022-12-13 00:56
Can you provide a short video where this issue is present so I can test my solution?

**Comment by hclivess** [comment] 2022-12-13 01:03
Or you can try this and let me know [nameer_i_frame.zip](https://github.com/hclivess/nameer/files/10213303/nameer_i_frame.zip)

**Comment by hclivess** [comment] 2022-12-13 01:06
Also please provide your output from the command you have specified, I am not working in Linux

**Comment by Deathproof76** [comment] 2022-12-13 09:06
I use Linux for my Server but I'm accessing it via a Windows machine (RDP/SSH/SMB). On Windows this should be useful in my particular case `ffprobe -show_frames problem.mkv -read_intervals %+30 -hide_banner | findstr pict_type=I`. The first 10 to 20 seconds may be enough also. [Here is some background on my particular problem. ](https://www.reddit.com/r/ffmpeg/comments/zjwm4r/trouble_with_ffmpeg_using_quicksync_encoded_files/) In short: Somehow only the first frame of the encoded file is an I-frame and the rest are only B-frames. That means that everytime you change position in the file during playback the decoder has to get there by decoding all the way back from the beginning of the file. It gets worse until absolutely unusable the larger the file is and also depending on from which device you're playing it.  

This a link for an [affected sample file](https://send.vis.ee/download/06403a4b159a5ccd/#6BjKFjmUrJAiKaMdxe3A8w) (it's the simpsons movie trailer). Also a working [intact sample](https://send.vis.ee/download/cfde2ac11c72ef2c/#-ycrQk0B2e9MU2vYAyctXA) for reference. 

The problematic sample produces the following:

`PS C:\Users\maxsc\Desktop\frame problem> ffprobe -show_frames problem.mkv -read_intervals %+30 -hide_banner | findstr pict_type=I`
```
Input #0, matroska,webm, from 'problem.mkv':
  Metadata:
    title           : The Simpsons Movie
    ARTIST          : Fox
    DATE_RELEASED   : 2007
    GENRE           : Trailer
    ENCODER         : Lavf59.34.101
  Duration: 00:02:17.28, start: 0.000000, bitrate: 2562 kb/s
  Stream #0:0: Video: hevc (Main), yuv420p(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc59.52.102 hevc_qsv
      DURATION        : 00:02:17.262000000
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Stereo
      DURATION        : 00:02:17.276000000
pict_type=I
```


The intact sample produces the following:

`PS C:\Users\maxsc\Desktop\frame problem> ffprobe -show_frames normal.mkv -read_intervals %+30 -hide_banner | findstr pict_type=I`
```
Input #0, matroska,webm, from 'normal.mkv':
  Metadata:
    title           : The Simpsons Movie
    DATE_RELEASED   : 2007
    creation_time   : 2022-12-12T11:16:57.000000Z
    ARTIST          : Fox
    GENRE           : Trailer
    ENCODER         : Lavf58.76.100
  Duration: 00:02:17.28, start: 0.000000, bitrate: 3160 kb/s
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:02:17.244000000
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Stereo
      DURATION        : 00:02:17.276000000
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
```

Thank you, for taking the time to look at this.

**Comment by hclivess** [comment] 2022-12-13 13:49
I am getting a stream error with the samples, please try it on full length video and let me know
This file for Windows: [nameer_i_frame.zip](https://github.com/hclivess/nameer/files/10218470/nameer_i_frame.zip) or Python: [nameer_i_frame (2).zip](https://github.com/hclivess/nameer/files/10218492/nameer_i_frame.2.zip), should work for all OS

I made the check for lower than 20 iframes, but the normal one has only 9

Here's what I have added:
```
    """iframe check"""
    i_frame_command = f'ffprobe -show_frames "{file}" -read_intervals %+30 -hide_banner'
    i_frame_process = subprocess.Popen(i_frame_command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    i_stdout, i_stderr = i_frame_process.communicate()
    i_return_code = i_frame_process.returncode
    i_pid = i_frame_process.pid
    i_frame_process.wait()

    i_out = str(i_stdout)
    i_prob_count = i_out.count("pict_type=I")
    print(f"I frames found: {i_prob_count}")

    if i_prob_count < 20:
        i_problem = "_problem"
    else:
        i_problem = ""

    """iframe check"""
```

**Comment by hclivess** [comment] 2022-12-13 13:52
This version checks for a minimum of 3 I frames : [nameer_i_frame_3_frames.zip](https://github.com/hclivess/nameer/files/10218515/nameer_i_frame_3_frames.zip)

**Comment by Deathproof76** [comment] 2022-12-13 15:33
When using the py from nameer_i_frame_3_frames.zip on an intact and full-length file it seems to work correctly as long as there are enough I-Frames to not trigger the append of "_problem".

```
C:\Users\maxsc\Desktop\frame problem - Kopie>python nameer_i_frame.py working.mkv
I frames found: 8
Base: working
Extension: .mkv
{'programs': [], 'streams': [{'index': 0, 'codec_name': 'hevc', 'codec_type': 'video', 'height': 804, 'r_frame_rate': '24/1', 'tags': {}}, {'index': 1, 'codec_name': 'eac3', 'codec_type': 'audio', 'channels': 6, 'r_frame_rate': '0/0', 'bit_rate': '768000', 'tags': {'language': 'eng'}}, {'index': 2, 'codec_name': 'subrip', 'codec_type': 'subtitle', 'r_frame_rate': '0/0', 'tags': {'language': 'eng'}}, {'index': 3, 'codec_name': 'subrip', 'codec_type': 'subtitle', 'r_frame_rate': '0/0', 'tags': {'language': 'eng'}}], 'format': {'filename': 'working.mkv', 'nb_streams': 4, 'nb_programs': 0, 'format_name': 'matroska,webm', 'format_long_name': 'Matroska / WebM', 'start_time': '0.000000', 'duration': '2590.304000', 'size': '898531278', 'bit_rate': '2775060', 'probe_score': 100, 'tags': {'title': 'Andor 01x05 - The Axe Forgets', 'creation_time': '2022-10-05T22:44:51.000000Z', 'ENCODER': 'Lavf58.45.100'}}}
```

When I take the same file but alter the `-read_intervals` from
`i_frame_command = f'ffprobe -show_frames "{file}" -read_intervals %+30 -hide_banner'`  to `i_frame_command = f'ffprobe -show_frames "{file}" -read_intervals %+10 -hide_banner'`  so that less than 3 i-frames are picked up, because not enough groups of frames where read in that time, it results in a keyerror:

```
C:\Users\maxsc\Desktop\frame problem - Kopie>python nameer_i_frame.py working.mkv
I frames found: 2
Base: working
Extension: .mkv
{}
Traceback (most recent call last):
  File "C:\Users\maxsc\Desktop\frame problem - Kopie\nameer_i_frame.py", line 51, in <module>
    for stream in json_all["streams"]:
KeyError: 'streams'
```

I don't know enough about programming to make an educated guess, but I think the problem may be due to the two separate processes being run. So that if the I-frame process "wins" and there is "_problem" to append, the code in line 51 (`for stream in json_all["streams"]`) tries to look in the output of the `ffprobe -show_frames` command and can't find it's values there, maybe.  I'm going to try more troubleshooting and will read up a bit more.

**Comment by hclivess** [comment] 2022-12-13 16:58
You are right, the problem is the two processes, I'll look into it

**Comment by hclivess** [comment] 2022-12-13 17:50
Problem was on my side, I was changing the input instead of the output, so the other process got wrong input. This should work:

[nameer_i_frame.zip](https://github.com/hclivess/nameer/files/10220741/nameer_i_frame.zip)

`normal_H264_800p_23fps_3086kbs_AAC_2ch.mkv`
`problem_HEVC_800p_23fps_2502kbs_AAC_2ch__i_frame_issue.mkv`

**Comment by Deathproof76** [comment] 2022-12-13 20:15
YES!!! It works! 
I adjusted two things to make batch operations easier: I changed `os.rename(file, output_file)` to `os.renames(file, output_file)` to be able to input full filepaths via terminal and I also had to change `new_file_values.insert(0, base_name.replace(" ", "_"))` to `new_file_values.insert(0, base_name.replace(" ", " "))`  so that folders with empty spaces would not be renamed.

That allows me to do add multiple files regardless of the filepath or subfolder

` PS C:\Users\maxsc\Desktop\frame problem> .\frame.py "C:\Users\maxsc\Desktop\frame problem\problem_e_ue - Kopie (8).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e_ue - Kopie (9).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e_ue - Kopie (10).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e_ue - Kopie (11).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e_ue - Kopie.mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e - Kopie (2).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e - Kopie (3).mkv" "C:\Users\maxsc\Desktop\frame problem\problem_e - Kopie (4).mkv"`

and every affected file gets flagged accordingly.

Goddamn, thank you! Can I buy you a coffee or something?

I'm currently testing with `dir /b /s *.mkv | findstr /e .mkv` which prints every mkv file with full filepath to find a way to automate it further. Tomorrow I'll begin testing on my server. I'm almost ashamed to admit it, but this may have to work on more than 55000 files.

**Comment by hclivess** [comment] 2022-12-13 23:07
Best of luck to your endeavors, whatever they may be. If you're into video transcoding, I made videer, which has some checks against errors. You can check it here: https://github.com/hclivess/videer

If you want any of these other changes merged (if they don't break anything else like cross-os compatibility), please submit a pull request.

You can enjoy the coffee on me 😉

**Closed as completed by hclivess** 2022-12-13 23:07 UTC
